# Generated by Django 3.0.6 on 2021-07-27 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210727_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gainlosschartdata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 13, 43, 20, 159479), null=True),
        ),
        migrations.AlterField(
            model_name='gainlosshistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 13, 43, 20, 156846), null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 13, 43, 20, 144052), null=True),
        ),
        migrations.AlterField(
            model_name='totalgainloss',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 13, 43, 20, 153344), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 13, 43, 20, 138965), null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 13, 43, 20, 151114), null=True),
        ),
    ]
