# Generated by Django 3.0.6 on 2021-07-28 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210727_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gainlosschartdata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 16, 59, 27, 263263), null=True),
        ),
        migrations.AlterField(
            model_name='gainlosshistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 16, 59, 27, 261663), null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 16, 59, 27, 255899), null=True),
        ),
        migrations.AlterField(
            model_name='totalgainloss',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 16, 59, 27, 260359), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 16, 59, 27, 253596), null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 16, 59, 27, 259408), null=True),
        ),
    ]
