# Generated by Django 3.0.6 on 2021-07-30 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210728_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gainlosschartdata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 1, 34, 59, 111092), null=True),
        ),
        migrations.AlterField(
            model_name='gainlosshistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 1, 34, 59, 110072), null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 1, 34, 59, 105960), null=True),
        ),
        migrations.AlterField(
            model_name='totalgainloss',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 1, 34, 59, 108978), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 1, 34, 59, 104415), null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 1, 34, 59, 108293), null=True),
        ),
    ]
