# Generated by Django 3.0.6 on 2021-08-19 11:52

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('daily_return', models.FloatField(blank=True, null=True)),
                ('cummeletive_return', models.FloatField(blank=True, null=True)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3000, null=True), blank=True, null=True, size=None)),
                ('stock_value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('portfolio_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.portfolio')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
