# Generated by Django 3.0.6 on 2021-08-12 07:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioperformance',
            name='symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3000, null=True), blank=True, null=True, size=None),
        ),
    ]
