# Generated by Django 3.0.6 on 2021-08-12 08:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_portfolioperformance_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioperformance',
            name='stock_value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
